import React, { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Download, FileText, Loader2, Printer, RefreshCw } from 'lucide-react'
import { useApp } from '../context/AppContext'
import { api } from '../services/api'
import { EmptyState, Panel, SectionHeading, SeverityBadge, StatusPill } from '../components/ui'
import { formatDateTime, riskBand } from '../utils/format'

export default function Reports() {
  const { id } = useParams()
  const { incidents, offline, pushToast } = useApp()
  const [report, setReport] = useState(null)
  const [busy, setBusy] = useState(false)
  const [selected, setSelected] = useState(id || incidents[0]?.id || '')

  useEffect(() => {
    if (id) setSelected(id)
  }, [id])

  useEffect(() => {
    if (!selected || offline) {
      setReport(null)
      return
    }
    let cancelled = false
    const load = async () => {
      setBusy(true)
      try {
        const data = await api.report(selected)
        if (!cancelled) setReport(data)
      } catch (err) {
        if (!cancelled) {
          setReport(null)
          pushToast({ type: 'error', title: 'Report generation failed', message: err.message })
        }
      } finally {
        if (!cancelled) setBusy(false)
      }
    }
    load()
    return () => {
      cancelled = true
    }
  }, [selected, offline, pushToast])

  const downloadHtml = () => {
    const node = document.getElementById('report-root')
    if (!node) return
    const styles = `
      body{font-family:Inter,Segoe UI,sans-serif;background:#fff;color:#111;margin:0;padding:32px;}
      h1{font-size:22px;margin:0 0 4px} h2{font-size:14px;text-transform:uppercase;letter-spacing:.12em;color:#0a8fb0;margin:26px 0 8px}
      .meta{color:#555;font-size:12px} .badge{display:inline-block;border:1px solid #ccc;border-radius:4px;padding:2px 8px;font-size:11px;margin-right:6px}
      table{width:100%;border-collapse:collapse;font-size:13px} td,th{border-bottom:1px solid #e5e7eb;padding:8px;text-align:left;vertical-align:top}
      .card{border:1px solid #e5e7eb;border-radius:8px;padding:14px;margin-bottom:12px}
      ol,ul{padding-left:18px;font-size:13px;line-height:1.6}
      .foot{margin-top:30px;font-size:11px;color:#6b7280;border-top:1px solid #e5e7eb;padding-top:12px}
    `
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${report?.id || 'Report'} — CyberVerse AI</title><style>${styles}</style></head><body>${node.outerHTML}<div class="foot">Generated by CyberVerse AI · ${new Date().toISOString()} · Simulated exercise data only</div></body></html>`
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${report?.id || 'cyberverse-report'}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    pushToast({ type: 'success', title: 'Report exported', message: `${a.download} downloaded.` })
  }

  const printable = useMemo(() => Boolean(report), [report])

  if (offline) {
    return (
      <div className="space-y-4">
        <SectionHeading eyebrow="Reporting" title="Security Reports" />
        <EmptyState
          title="Reports require the backend"
          message="Start the FastAPI service to generate incident reports from live detection data."
        />
      </div>
    )
  }

  return (
    <div className="space-y-4">
      <SectionHeading
        eyebrow="Reporting"
        title="Security Reports"
        description="One-page incident report with executive summary, evidence, timeline, AI analysis, response plan and containment status."
        actions={
          <>
            <button className="btn-ghost text-xs" onClick={() => setSelected(id || selected)} disabled={busy}>
              <RefreshCw size={14} className={busy ? 'animate-spin' : ''} /> Regenerate
            </button>
            <button className="btn-ghost text-xs" onClick={() => window.print()} disabled={!printable}>
              <Printer size={14} /> Export PDF
            </button>
            <button className="btn-primary text-xs" onClick={downloadHtml} disabled={!printable}>
              <Download size={14} /> Export report
            </button>
          </>
        }
      />

      <div className="flex flex-wrap items-center gap-2">
        <label className="label-caps" htmlFor="report-incident">Incident</label>
        <select
          id="report-incident"
          className="input w-auto min-w-[320px] py-1.5 text-xs"
          value={selected}
          onChange={(e) => setSelected(e.target.value)}
        >
          <option value="">Select an incident…</option>
          {incidents.map((i) => (
            <option key={i.id} value={i.id}>
              {i.id} — {i.threat_type} ({i.status})
            </option>
          ))}
        </select>
        {selected && (
          <Link to={`/app/incidents/${selected}`} className="text-[12px] text-cyber-400 hover:text-cyber-300">
            Open case →
          </Link>
        )}
      </div>

      {busy && !report ? (
        <div className="flex h-40 items-center justify-center gap-2 text-slate-400">
          <Loader2 size={18} className="animate-spin" /> Generating report…
        </div>
      ) : !report ? (
        <EmptyState
          icon={<FileText size={24} />}
          title="No report selected"
          message="Choose an incident above to build its security report."
        />
      ) : (
        <article id="report-root" className="card mx-auto max-w-4xl p-6 sm:p-8">
          <header className="flex flex-wrap items-start justify-between gap-3 border-b border-white/[0.08] pb-4">
            <div>
              <p className="label-caps">CyberVerse AI · Incident report</p>
              <h2 className="mt-1 text-xl font-semibold text-white">{report.title}</h2>
              <p className="mono mt-1 text-[11.5px] text-slate-500">
                {report.id} · generated {formatDateTime(report.generated_at)} · {report.generated_by}
              </p>
            </div>
            <div className="flex flex-col items-end gap-1">
              <SeverityBadge severity={report.severity} />
              <StatusPill status={report.status} />
              <span className="mono text-[11px]" style={{ color: riskBand(report.risk_score).color }}>
                risk {report.risk_score}/100
              </span>
            </div>
          </header>

          <p className="mt-4 rounded-lg border border-white/[0.07] bg-white/[0.02] p-3 text-[13.5px] leading-relaxed text-slate-300">
            {report.executive_summary}
          </p>

          <section className="mt-5 grid gap-3 sm:grid-cols-2">
            <Panel title="Incident summary">
              <table className="w-full text-[12.5px]">
                <tbody>
                  {[
                    ['Threat type', report.threat_type],
                    ['Severity', report.severity],
                    ['Risk score', `${report.risk_score}/100`],
                    ['Status', report.status],
                    ['Source', report.source],
                    ['First seen', formatDateTime(report.first_seen)],
                    ['Last seen', formatDateTime(report.last_seen)],
                    ['Affected assets', report.affected_assets.join(', ')],
                  ].map(([k, v]) => (
                    <tr key={k}>
                      <td className="py-1.5 pr-3 text-slate-500">{k}</td>
                      <td className="py-1.5 text-slate-200">{v}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </Panel>

            <Panel title="Attack path">
              {report.attack_path.length ? (
                <ol className="space-y-1.5 text-[12.5px]">
                  {report.attack_path.map((p, i) => (
                    <li key={i} className="flex items-center gap-2">
                      <span className="mono text-cyber-500">{String(i + 1).padStart(2, '0')}</span>
                      <span className="text-slate-300">{p}</span>
                      {i < report.attack_path.length - 1 && <span className="text-slate-600">↓</span>}
                    </li>
                  ))}
                </ol>
              ) : (
                <p className="text-[12.5px] text-slate-500">No attack graph recorded.</p>
              )}
            </Panel>
          </section>

          <section className="mt-5">
            <h3 className="label-caps mb-2">Evidence</h3>
            <ul className="space-y-1.5 text-[13px] text-slate-300">
              {report.evidence.map((e, i) => (
                <li key={i} className="flex gap-2">
                  <span className="text-cyber-500">▸</span> {e}
                </li>
              ))}
            </ul>
          </section>

          <section className="mt-5">
            <h3 className="label-caps mb-2">AI analysis</h3>
            <p className="text-[13.5px] leading-relaxed text-slate-300">{report.ai_analysis.summary}</p>
            <div className="mt-3 grid gap-3 sm:grid-cols-2">
              {report.ai_analysis.sections.map((s, i) => (
                <div key={i} className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3">
                  <p className="label-caps mb-1">{s.heading}</p>
                  <p className="whitespace-pre-line text-[12.5px] leading-relaxed text-slate-400">{s.body}</p>
                </div>
              ))}
            </div>
          </section>

          <section className="mt-5">
            <h3 className="label-caps mb-2">Recommended response</h3>
            <ol className="space-y-1.5 text-[13px] text-slate-300">
              {report.recommendations.map((r, i) => (
                <li key={i}>
                  <span className="font-medium text-slate-200">{r.title}</span> — {r.detail}
                  <span className="mono ml-2 text-[10px] uppercase text-slate-500">{r.priority}</span>
                </li>
              ))}
            </ol>
          </section>

          <section className="mt-5">
            <h3 className="label-caps mb-2">Containment status</h3>
            {report.containment ? (
              <div className="rounded-lg border border-cyber-400/30 bg-cyber-400/[0.06] p-3">
                <p className="text-[13.5px] font-semibold text-cyber-300">
                  CONTAINED · {formatDateTime(report.containment.at)} by {report.containment.by}
                </p>
                <ul className="mt-2 grid gap-1 text-[12.5px] text-slate-300 sm:grid-cols-2">
                  {report.containment.actions.map((a) => (
                    <li key={a}>✓ {a}</li>
                  ))}
                </ul>
              </div>
            ) : (
              <p className="text-[13px] text-warn-400">
                Not contained — the incident remains {report.status.toLowerCase()} and requires analyst action.
              </p>
            )}
          </section>

          <section className="mt-5">
            <h3 className="label-caps mb-2">Timeline</h3>
            <table className="w-full text-[12.5px]">
              <thead>
                <tr className="border-b border-white/[0.08] text-[10.5px] uppercase tracking-wider text-slate-500">
                  <th className="py-1.5 text-left">Time</th>
                  <th className="py-1.5 text-left">Type</th>
                  <th className="py-1.5 text-left">Event</th>
                </tr>
              </thead>
              <tbody>
                {report.timeline.slice(0, 14).map((t, i) => (
                  <tr key={i} className="border-b border-white/[0.04]">
                    <td className="mono py-1.5 pr-3 text-slate-500">{formatDateTime(t.time)}</td>
                    <td className="mono py-1.5 pr-3 text-cyber-500">{t.kind}</td>
                    <td className="py-1.5 text-slate-300">
                      {t.label}
                      {t.detail && <span className="mono block text-[11px] text-slate-600">{t.detail}</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          <footer className="mt-6 border-t border-white/[0.08] pt-3 text-[11.5px] text-slate-500">
            {report.classification} · {report.notice}
          </footer>
        </article>
      )}
    </div>
  )
}
